### ISSUE TITLE
input line descends at exactly 10 characters

### ISSUE THREAD

**Issue by juped** [urbit/talk#27]
Safari 9.1.1, OS X 10.11.5

![89c5vos1wg](https://cloud.githubusercontent.com/assets/115765/16817649/9260f2a0-48f8-11e6-9016-3c1a8c028277.gif)

**Comment by galenwp** [comment]
This is super weird, and Safari-specific.  But I did just confirm it to be real.

**Comment by Fang-** [comment]
Looks like an auto-width issue.

Safari's inspector says the auto-width is calculated as `67.5 px`. Apparently it doesn't round this up, because manually setting the width to `68 px` displays fine.  
(It's extra strange because I'm on a high-dpi display and Safari should know how to work with half pixels in that case, right?)

Possible solution here would be just hard-coding the width of that element to `96 px` which accommodates four digits. Not sure if such a "hack" is desirable though.

**Comment by galenwp** [comment]
Actually, setting it's width probably is the right thing to do here.  Call it `120px`.
